### ISSUE TITLE
add validations & all associations

### ISSUE THREAD

**Issue by tia-garibaldi** [Stef1380/flavr#11]

**Comment by TomGourdon** [comment]
Validations : 

Avatar : Mettre un avatar_url obligatoire
Diet : Pas de diet obligatoire?
Ingredient_recipe : Mettre une quantity obligatoire
Ingredient : Mettre un nom et kcal obligatoire
Preference : Pas de like obligatoire?
Profil : Mettre un username, un sexe, un age obligatoire 
Recipe : Mettre un nom et un description obligatoire
Restriction : rien
Restriction : Mettre une restriction obligatoire
Target : Mettre un objectif obligatoire
User : Mettre un email et mdp obligatoire et unique et mettre un nom et prenom obligatoire

**Comment by TomGourdon** [comment]
Validations :

Avatar : Mettre un avatar_url obligatoire
Diet : rien
Ingredient_recipe : Mettre une quantity obligatoire
Ingredient : Mettre un nom et kcal obligatoire
Preference : like obligatoire
Profil : Mettre un username et age obligatoire
Recipe : Mettre un nom et un description obligatoire
Restriction profils: rien
Restriction : rien
Target : Mettre un objectif obligatoire
User : Mettre un email et mdp obligatoire et unique et mettre un nom et prenom obligatoire

**Comment by TomGourdon** [comment]
Validations :

Avatar : Mettre un avatar_url obligatoire
Diet : rien
Ingredient_recipe : Mettre une quantity obligatoire
Ingredient : Mettre un nom et kcal obligatoire
Preference : rien
Profil : Mettre un username et age obligatoire
Recipe : Mettre un nom et un description obligatoire
Restriction profils: rien
Restriction : rien
Target : Mettre un objectif obligatoire
User : Mettre un email et mdp obligatoire et unique et mettre un nom et prenom obligatoire

**Comment by TomGourdon** [comment]
Validations :

Avatar : Mettre un avatar_url obligatoire
Diet : mettre une diet obligatoire
Ingredient_recipe : Mettre une quantity obligatoire
Ingredient : Mettre un nom et kcal obligatoire
Preference : rien
Profil : Mettre un username et age obligatoire
Recipe : Mettre un nom et un description obligatoire
Restriction profils: rien
Restriction : rien
Target : Mettre un objectif obligatoire
User : Mettre un email et mdp obligatoire et unique et mettre un nom et prenom obligatoire
